site_name: Next Step blog

theme:
    logo: assets/logo1.png
    favicon: assets/logo1.png
    name: 'material'
    custom_dir: custom_theme
    shortcuts:
      help: 191 # ?
      next: 78 # n
      previous: 80 # p
      search: 83 # s
    font:
      text: Cambria", "Georgia", "Times New Roman", "Serif
      code: Roboto Mono
    palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - toc:
      permalink: '#'

plugins:
  - search
  - roamlinks 

extra_css:
  - stylesheets/extra.css
  - stylesheets/tags.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/customScript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=63761cc6c27003d6f03e0634